### ISSUE TITLE
removeEventListener on component umount

### ISSUE THREAD

**Issue by icaromh** [diogomoretti/react-snakke#1]
First of all, that's an awesome job! Really simple but elegant. 👏

Maybe it's a good idea to remove this listener on component umount.

https://github.com/diogomoretti/react-snakke/blob/0c8dea1b23e9d43dbc81e24d18567680a469acf2/src/index.js#L38-L40
___

`good first issue` tag?

**Comment by diogomoretti** [comment]
Thanks... I think it's a `good first issue` too =]
